# Generated by Django 5.1.1 on 2024-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('http_method', models.CharField(max_length=10)),
                ('uri', models.TextField()),
                ('response_code', models.IntegerField()),
                ('response_size', models.IntegerField()),
                ('http_version', models.CharField(max_length=10)),
                ('remote_user', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
